"""
Polymarket Trading Bot - Main Module

This bot monitors BTC price prediction markets on Polymarket and executes
trades based on technical indicators (green candles with above-average volume).

Strategy:
    - Monitor 5-minute BTC price prediction markets
    - Trade when: green candle (close > open) AND volume > 20-period average
    - Only trade active markets with sufficient liquidity

Usage:
    python bot.py

Author: Generated by Magnus AI
"""

import time
import math
from typing import Optional, Any
from decimal import Decimal

import requests
import pandas as pd

from config import (
    POLYMARKET_API_KEY,
    POLYMARKET_API_SECRET,
    POLYMARKET_CHAIN_ID,
    TRADE_SIZE_USDC,
    MIN_MARKET_LIQUIDITY,
    VOLUME_THRESHOLD_MULTIPLIER,
    VOLUME_AVERAGE_PERIODS,
    BTC_MARKET_KEYWORDS,
    MARKET_REFRESH_INTERVAL,
    CANDLE_TIMEFRAME_MINUTES,
    MAX_RETRIES,
    INITIAL_RETRY_DELAY,
    RETRY_BACKOFF_MULTIPLIER,
)
from logger import (
    logger,
    log_action,
    log_trade,
    log_error,
    log_market_scan,
    log_signal,
    log_api_request,
    log_api_response,
)


class PolymarketAPIError(Exception):
    """Custom exception for Polymarket API errors."""
    pass


class InsufficientBalanceError(Exception):
    """Custom exception for insufficient balance errors."""
    pass


class PolymarketClient:
    """
    Polymarket CLOB API client wrapper.

    Handles authentication, request retries, and common operations.
    """

    def __init__(self, api_key: str, api_secret: str, chain_id: int = 137):
        """
        Initialize the Polymarket client.

        Args:
            api_key: Polymarket API key.
            api_secret: Polymarket API secret.
            chain_id: Chain ID (137 for Polygon mainnet).
        """
        self.api_key = api_key
        self.api_secret = api_secret
        self.chain_id = chain_id
        self.base_url = "https://clob.polymarket.com"
        self.session = requests.Session()
        self.session.headers.update({
            "POLY-ADDRESS": api_key,
            "POLY-SIGNATURE": api_secret,
            "Content-Type": "application/json",
        })

    def _make_request(
        self,
        method: str,
        endpoint: str,
        params: Optional[dict] = None,
        data: Optional[dict] = None
    ) -> dict[str, Any]:
        """
        Make an authenticated request to the Polymarket API with retry logic.

        Args:
            method: HTTP method (GET, POST, etc.).
            endpoint: API endpoint path.
            params: Query parameters for GET requests.
            data: Request body for POST requests.

        Returns:
            JSON response as dictionary.

        Raises:
            PolymarketAPIError: If the request fails after all retries.
            InsufficientBalanceError: If the error is due to insufficient balance.
        """
        url = f"{self.base_url}{endpoint}"
        log_api_request(method, endpoint, params)

        retry_delay = INITIAL_RETRY_DELAY
        last_error = None

        for attempt in range(MAX_RETRIES):
            try:
                start_time = time.time()
                response = self.session.request(
                    method=method,
                    url=url,
                    params=params,
                    json=data,
                    timeout=30
                )
                response_time_ms = (time.time() - start_time) * 1000

                log_api_response(
                    response.status_code,
                    response_time_ms,
                    response.ok
                )

                if response.status_code == 429:  # Rate limited
                    retry_after = int(response.headers.get("Retry-After", retry_delay))
                    logger.warning(f"Rate limited, waiting {retry_after}s")
                    time.sleep(retry_after)
                    continue

                if response.status_code == 402:  # Insufficient balance
                    raise InsufficientBalanceError("Insufficient USDC balance for trade")

                response.raise_for_status()
                return response.json()

            except requests.exceptions.RequestException as e:
                last_error = e
                logger.warning(
                    f"Request failed (attempt {attempt + 1}/{MAX_RETRIES}): {e}"
                )
                if attempt < MAX_RETRIES - 1:
                    time.sleep(retry_delay)
                    retry_delay *= RETRY_BACKOFF_MULTIPLIER

        raise PolymarketAPIError(f"Request failed after {MAX_RETRIES} retries: {last_error}")

    def get_markets(self, keywords: Optional[list[str]] = None) -> list[dict[str, Any]]:
        """
        Fetch active markets, optionally filtered by keywords.

        Args:
            keywords: List of keywords to filter markets by.

        Returns:
            List of market dictionaries.
        """
        params = {"active": "true"}
        response = self._make_request("GET", "/markets", params=params)
        markets = response.get("markets", [])

        if keywords:
            filtered = []
            for market in markets:
                question = market.get("question", "").lower()
                description = market.get("description", "").lower()
                if any(kw.lower() in question or kw.lower() in description
                       for kw in keywords):
                    filtered.append(market)
            return filtered

        return markets

    def get_market(self, market_id: str) -> dict[str, Any]:
        """
        Fetch a single market by ID.

        Args:
            market_id: The market ID to fetch.

        Returns:
            Market dictionary.
        """
        return self._make_request("GET", f"/markets/{market_id}")

    def get_order_book(self, market_id: str) -> dict[str, Any]:
        """
        Fetch the order book for a market.

        Args:
            market_id: The market ID.

        Returns:
            Order book dictionary with bids and asks.
        """
        return self._make_request("GET", f"/orderbook/{market_id}")

    def get_price_history(
        self,
        market_id: str,
        interval: str = "5m",
        limit: int = 100
    ) -> list[dict[str, Any]]:
        """
        Fetch price history (candlestick data) for a market.

        Args:
            market_id: The market ID.
            interval: Candlestick interval (e.g., "5m", "1h", "1d").
            limit: Number of candles to fetch.

        Returns:
            List of candle dictionaries with open, high, low, close, volume.
        """
        params = {"interval": interval, "limit": limit}
        response = self._make_request(
            "GET",
            f"/markets/{market_id}/price-history",
            params=params
        )
        return response.get("candles", [])

    def get_balance(self) -> float:
        """
        Fetch current USDC balance.

        Returns:
            Balance in USDC.
        """
        response = self._make_request("GET", "/balance")
        return float(response.get("balance", 0))

    def place_order(
        self,
        market_id: str,
        side: str,  # "YES" or "NO"
        price: float,
        size: float
    ) -> dict[str, Any]:
        """
        Place a limit order on a market.

        Args:
            market_id: The market ID to trade.
            side: "YES" or "NO" outcome.
            price: Limit price (0.0 to 1.0).
            size: Size in USDC.

        Returns:
            Order response with order_id.
        """
        # Ensure price is within valid range
        price = max(0.01, min(0.99, price))

        data = {
            "market": market_id,
            "side": side.upper(),
            "price": str(Decimal(str(price)).quantize(Decimal("0.01"))),
            "size": str(size),
            "expiration": int(time.time()) + 3600,  # 1 hour expiration
        }

        log_action("Placing order", {
            "market": market_id,
            "side": side,
            "price": price,
            "size": size
        })

        response = self._make_request("POST", "/order", data=data)

        log_trade(
            market_id=market_id,
            market_question="",
            side=side,
            price=price,
            size=size,
            outcome="BUY",
            order_id=response.get("order_id")
        )

        return response

    def get_market_liquidity(self, market_id: str) -> float:
        """
        Calculate total liquidity for a market.

        Args:
            market_id: The market ID.

        Returns:
            Total liquidity in USDC.
        """
        order_book = self.get_order_book(market_id)
        liquidity = 0.0

        for bid in order_book.get("bids", []):
            liquidity += float(bid.get("size", 0)) * float(bid.get("price", 0))

        for ask in order_book.get("asks", []):
            liquidity += float(ask.get("size", 0)) * (1 - float(ask.get("price", 0)))

        return liquidity


class MarketScanner:
    """
    Scans Polymarket for eligible BTC price prediction markets.
    """

    def __init__(self, client: PolymarketClient):
        """
        Initialize the market scanner.

        Args:
            client: PolymarketClient instance.
        """
        self.client = client

    def find_eligible_markets(self) -> list[dict[str, Any]]:
        """
        Find all markets that meet trading eligibility criteria.

        Returns:
            List of eligible market dictionaries.
        """
        log_action("Scanning for BTC markets")

        # Fetch BTC-related markets
        markets = self.client.get_markets(keywords=BTC_MARKET_KEYWORDS)
        log_market_scan(len(markets), 0)

        eligible = []
        for market in markets:
            if self._is_market_eligible(market):
                eligible.append(market)

        log_market_scan(len(markets), len(eligible))
        return eligible

    def _is_market_eligible(self, market: dict[str, Any]) -> bool:
        """
        Check if a market meets eligibility criteria.

        Args:
            market: Market dictionary to check.

        Returns:
            True if market is eligible for trading.
        """
        # Check if market is active
        if not market.get("active", False):
            return False

        # Check if market has resolved
        if market.get("resolved", False):
            return False

        # Check liquidity
        market_id = market.get("condition_id") or market.get("id")
        if market_id:
            try:
                liquidity = self.client.get_market_liquidity(market_id)
                if liquidity < MIN_MARKET_LIQUIDITY:
                    return False
            except Exception as e:
                log_error(e, f"Checking liquidity for {market_id}")
                return False

        return True


class SignalGenerator:
    """
    Generates trading signals based on technical analysis.
    """

    def __init__(self, client: PolymarketClient):
        """
        Initialize the signal generator.

        Args:
            client: PolymarketClient instance.
        """
        self.client = client

    def analyze_market(self, market_id: str) -> Optional[dict[str, Any]]:
        """
        Analyze a market for trading signals.

        Args:
            market_id: The market ID to analyze.

        Returns:
            Signal dictionary if signal found, None otherwise.
        """
        try:
            # Fetch price history
            candles = self.client.get_price_history(
                market_id,
                interval=f"{CANDLE_TIMEFRAME_MINUTES}m",
                limit=VOLUME_AVERAGE_PERIODS + 10
            )

            if len(candles) < VOLUME_AVERAGE_PERIODS:
                return None

            # Convert to DataFrame for analysis
            df = pd.DataFrame(candles)
            df["open"] = pd.to_numeric(df["open"])
            df["close"] = pd.to_numeric(df["close"])
            df["high"] = pd.to_numeric(df["high"])
            df["low"] = pd.to_numeric(df["low"])
            df["volume"] = pd.to_numeric(df["volume"])

            # Calculate indicators
            df["avg_volume"] = df["volume"].rolling(VOLUME_AVERAGE_PERIODS).mean()

            # Get the most recent candle
            current = df.iloc[-1]
            current_open = current["open"]
            current_close = current["close"]
            current_volume = current["volume"]
            avg_volume = current["avg_volume"]

            # Check for green candle
            is_green_candle = current_close > current_open

            # Check for above-average volume
            volume_threshold = avg_volume * VOLUME_THRESHOLD_MULTIPLIER
            is_high_volume = current_volume > volume_threshold

            # Log signal if conditions met
            if is_green_candle and is_high_volume:
                log_signal(
                    market_id=market_id,
                    signal_type="GREEN_CANDLE_HIGH_VOLUME",
                    candle_data={
                        "open": current_open,
                        "close": current_close,
                        "high": current["high"],
                        "low": current["low"],
                    },
                    volume_data={
                        "current": current_volume,
                        "average": avg_volume,
                        "threshold": volume_threshold,
                    }
                )

                return {
                    "signal": True,
                    "type": "GREEN_CANDLE_HIGH_VOLUME",
                    "side": "YES",
                    "price": min(current_close + 0.02, 0.99),  # Slightly above current
                    "market_id": market_id,
                }

            return None

        except Exception as e:
            log_error(e, f"Analyzing market {market_id}")
            return None


class TradingBot:
    """
    Main trading bot that coordinates market scanning, signal generation, and execution.
    """

    def __init__(self):
        """Initialize the trading bot with all required components."""
        log_action("Initializing Polymarket Trading Bot")

        self.client = PolymarketClient(
            api_key=POLYMARKET_API_KEY,
            api_secret=POLYMARKET_API_SECRET,
            chain_id=POLYMARKET_CHAIN_ID
        )
        self.scanner = MarketScanner(self.client)
        self.signal_generator = SignalGenerator(self.client)

        self.running = False
        self.trades_executed = 0

    def start(self) -> None:
        """
        Start the main trading loop.

        This runs indefinitely until stopped, scanning markets and executing trades.
        """
        log_action("Bot started")
        self.running = True

        while self.running:
            try:
                self._run_trading_cycle()
            except KeyboardInterrupt:
                self.running = False
                log_action("Bot stopped by user")
                break
            except Exception as e:
                log_error(e, "Main trading loop")
                time.sleep(10)  # Wait before retrying

            # Wait for next cycle
            time.sleep(MARKET_REFRESH_INTERVAL)

    def _run_trading_cycle(self) -> None:
        """
        Execute a single trading cycle:
        1. Scan for eligible markets
        2. Analyze each market for signals
        3. Execute trades for valid signals
        """
        log_action("Starting trading cycle")

        # Check balance before trading
        try:
            balance = self.client.get_balance()
            log_action(f"Current balance: {balance:.2f} USDC")

            if balance < TRADE_SIZE_USDC:
                logger.warning(f"Insufficient balance: {balance:.2f} < {TRADE_SIZE_USDC}")
                return
        except Exception as e:
            log_error(e, "Checking balance")
            return

        # Find eligible markets
        markets = self.scanner.find_eligible_markets()

        if not markets:
            log_action("No eligible markets found")
            return

        # Analyze each market for signals
        for market in markets:
            market_id = market.get("condition_id") or market.get("id")
            market_question = market.get("question", "Unknown")

            if not market_id:
                continue

            log_action(f"Analyzing market", {
                "id": market_id,
                "question": market_question[:50]
            })

            signal = self.signal_generator.analyze_market(market_id)

            if signal and signal.get("signal"):
                self._execute_trade(market_id, market_question, signal)

    def _execute_trade(
        self,
        market_id: str,
        market_question: str,
        signal: dict[str, Any]
    ) -> bool:
        """
        Execute a trade based on a signal.

        Args:
            market_id: The market ID to trade.
            market_question: The market question for logging.
            signal: Signal dictionary with trade details.

        Returns:
            True if trade was executed successfully.
        """
        try:
            log_action("Executing trade", {
                "market": market_id,
                "side": signal["side"],
                "price": signal["price"],
                "size": TRADE_SIZE_USDC
            })

            response = self.client.place_order(
                market_id=market_id,
                side=signal["side"],
                price=signal["price"],
                size=TRADE_SIZE_USDC
            )

            log_trade(
                market_id=market_id,
                market_question=market_question,
                side=signal["side"],
                price=signal["price"],
                size=TRADE_SIZE_USDC,
                outcome="BUY",
                order_id=response.get("order_id")
            )

            self.trades_executed += 1
            log_action(f"Trade executed successfully. Total trades: {self.trades_executed}")
            return True

        except InsufficientBalanceError as e:
            log_error(e, "Insufficient balance for trade")
            return False

        except PolymarketAPIError as e:
            log_error(e, "API error during trade execution")
            return False

        except Exception as e:
            log_error(e, "Unexpected error during trade execution")
            return False

    def stop(self) -> None:
        """Stop the trading bot gracefully."""
        log_action("Stopping bot")
        self.running = False


def main() -> None:
    """
    Main entry point for the trading bot.

    Creates bot instance and starts the main trading loop.
    """
    logger.info("=" * 80)
    logger.info("POLYMARKET TRADING BOT - STARTING")
    logger.info("=" * 80)
    logger.info(f"Trade Size: {TRADE_SIZE_USDC} USDC")
    logger.info(f"Min Liquidity: {MIN_MARKET_LIQUIDITY} USDC")
    logger.info(f"Volume Threshold: {VOLUME_THRESHOLD_MULTIPLIER}x average")
    logger.info(f"Candle Timeframe: {CANDLE_TIMEFRAME_MINUTES} minutes")
    logger.info(f"Refresh Interval: {MARKET_REFRESH_INTERVAL} seconds")
    logger.info("=" * 80)

    bot = TradingBot()

    try:
        bot.start()
    except KeyboardInterrupt:
        bot.stop()
        logger.info("Bot stopped gracefully")
    except Exception as e:
        log_error(e, "Fatal error in main")
        bot.stop()
        raise


if __name__ == "__main__":
    main()
